/*
 * This file is part of jc, http://www.jcommander.narod.ru
 * Copyright (C) 2005-2010 Pavel Ovcharov
 *
 * jc is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RewriteDialog.java
 *
 * Created on 22.06.2009, 15:06:22
 */

package omegaCommander.gui.dialog;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDialog;
import omegaCommander.fileSystem.BaseFile;
import omegaCommander.util.LanguageBundle;

/**
 *
 * @author Programmer
 */
public class RewriteDialog extends javax.swing.JDialog {

    public enum ReplaceResult {REPLACE, REPLACE_OLD, SKIP, CANCEL};
	ReplaceResult dialogResult;

	/** Creates new form RewriteDialog */
    public RewriteDialog(JDialog parent, BaseFile source, BaseFile target) {
        super(parent, true);
        initComponents();
		setLocationRelativeTo(parent);
//		setResizable(false);

		setSize(500, 330);

		LanguageBundle lb = LanguageBundle.getInstance();

		jButtonYes.addActionListener(new ButtonListener(this, ReplaceResult.REPLACE));
		jButtonYes.addKeyListener(new ButtonKeyListener(this));
		jButtonNo.addActionListener(new ButtonListener(this, ReplaceResult.SKIP));
		jButtonNo.addKeyListener(new ButtonKeyListener(this));
		jButtonCancel.addActionListener(new ButtonListener(this, ReplaceResult.CANCEL));
		jButtonCancel.addKeyListener(new ButtonKeyListener(this));

		jCheckBoxApplyToAll.addKeyListener(new ComponentKeyListener(this, jButtonYes));
		jCheckBoxApplyToOlder.addKeyListener(new ComponentKeyListener(this, jButtonYes));
		jCheckBoxApplyToAll.addKeyListener(new CursorKeyListener());
		jCheckBoxApplyToOlder.addKeyListener(new CursorKeyListener());

		jButtonYes.setText(lb.getString("StrOk"));
		jButtonNo.setText(lb.getString("StrSkip"));
		jButtonCancel.setText(lb.getString("StrCancel"));

		setTitle(LanguageBundle.getInstance().getString("StrFileExist"));

//		jLabelHeader.setText(lb.getString("StrReplaceThisFile"));
		jLabel2.setText(lb.getString("StrReplaceThisFile") + " " + lb.getString("StrCurrentFile"));
//		jLabel1.setText(target.getAbsolutePath());
//		jTextPane1.setVisible(false);
		jTextPane1.setText(target.getAbsolutePath());
		jLabel4.setText( String.format(lb.getString("StrDateSize"), target.getFormatFileSize(), target.getLastModifiedDate()));

		jLabel3.setText(lb.getString("StrNewFile"));
		jTextPane2.setText(source.getAbsolutePath());
		jLabel6.setText(String.format(lb.getString("StrDateSize"), source.getFormatFileSize(), source.getLastModifiedDate()));
		jCheckBoxApplyToAll.setText(lb.getString("StrApplyToAll"));
		jCheckBoxApplyToOlder.setText(lb.getString("StrAplyToOlder"));

//		String path = target.getAbsolutePath();
//		int realWidth = jLabelFilename.getFontMetrics(jLabelFilename.getFont()).stringWidth(path);
//
//		if (jLabelFilename.getWidth()< realWidth) {
//			jLabelFilename.setText(path.substring(0, 25) + "... " + path.substring(path.length()-25, path.length()));
//		}

    }

	public boolean getApplyToAll() {
		return jCheckBoxApplyToAll.isSelected();
	}

	public boolean getApplyToOlder() {
		return jCheckBoxApplyToOlder.isSelected();
	}

	public ReplaceResult getDialogResult() {
		return dialogResult;
	}


	private class ButtonListener implements ActionListener{
		private ReplaceResult result;
		private JDialog parent;
		public ButtonListener(JDialog parent, ReplaceResult result) {
			this.result = result;
			this.parent = parent;
		}

		public void actionPerformed(ActionEvent e) {

			dialogResult = result;
			parent.setVisible(false);
		}
	}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelCheckBox = new javax.swing.JPanel();
        jCheckBoxApplyToAll = new javax.swing.JCheckBox();
        jCheckBoxApplyToOlder = new javax.swing.JCheckBox();
        jPanelButtons = new javax.swing.JPanel();
        jButtonYes = new javax.swing.JButton();
        jButtonNo = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel2.setText("Существующий: ");
        jPanel2.add(jLabel2);

        getContentPane().add(jPanel2);

        jScrollPane1.setBorder(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(435, 18));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(435, 18));

        jTextPane1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jTextPane1.setBorder(null);
        jTextPane1.setEditable(false);
        jTextPane1.setText("text");
        jTextPane1.setFocusable(false);
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 5));

        jLabel4.setText("jLabel4");
        jPanel5.add(jLabel4);

        getContentPane().add(jPanel5);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel3.setText("Новый:");
        jPanel3.add(jLabel3);

        getContentPane().add(jPanel3);

        jScrollPane2.setBorder(null);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(435, 18));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(435, 18));

        jTextPane2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jTextPane2.setBorder(null);
        jTextPane2.setEditable(false);
        jTextPane2.setText("text");
        jTextPane2.setFocusable(false);
        jScrollPane2.setViewportView(jTextPane2);

        getContentPane().add(jScrollPane2);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 5));

        jLabel6.setText("jLabel1");
        jPanel7.add(jLabel6);

        getContentPane().add(jPanel7);

        jPanelCheckBox.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 15));

        jCheckBoxApplyToAll.setText("Применить ко всем");
        jPanelCheckBox.add(jCheckBoxApplyToAll);

        jCheckBoxApplyToOlder.setText("Применить к устаревшим");
        jPanelCheckBox.add(jCheckBoxApplyToOlder);

        getContentPane().add(jPanelCheckBox);

        jButtonYes.setText("Да");
        jButtonYes.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanelButtons.add(jButtonYes);

        jButtonNo.setText("Пропустить");
        jButtonNo.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanelButtons.add(jButtonNo);

        jButtonCancel.setText("Отмена");
        jButtonCancel.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanelButtons.add(jButtonCancel);

        getContentPane().add(jPanelButtons);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonNo;
    private javax.swing.JButton jButtonYes;
    private javax.swing.JCheckBox jCheckBoxApplyToAll;
    private javax.swing.JCheckBox jCheckBoxApplyToOlder;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelCheckBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables

}
